version: "3.4"

services:

  # The Application
  app:
    container_name: mariolaps_app
    image: php:alpine
    volumes:
      - ./storage:/var/www/storage
    working_dir: /app
    env_file: '.env.production'
    ports:
      - 3456:8000
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    expose:
      - 9000

  # The Database
  database:
    container_name: mariolaps_database
    image: mysql:5.7.19
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mariolaps
      - MYSQL_USER=mariolaps
      - MYSQL_PASSWORD=password
    ports:
      - 3457:3306

  # The Web Server
  web:
    container_name: mariolaps_nginx
    build:
      context: ./
      dockerfile: docker/web.Dockerfile
    volumes:
      - ./storage/logs/:/var/log/nginx
    ports:
      - 3458:80

volumes:
  db_volume:
